name: "Run Pytest on Commit"
on:
  push:
    branches:
      - dev
jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Run tests"
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -q "pytest:api" || echo "${{ github.event.head_commit.message }}" | grep -q "pytest:database"; then
            pytest -m "api or database"
          elif echo "${{ github.event.head_commit.message }}" | grep -q "pytest:price_info"; then
            pytest -m "price_info"
          elif echo "${{ github.event.head_commit.message }}" | grep -q "pytest:database"; then
            pytest -m "price_info"
          else
            pytest
          fi
